Fix back compat deserializing nan/inf counts in ColumnCountsMetric (#1185)
## Description

fixes #1184 

Fix back compat deserializing nan/inf counts in ColumnCountsMetric to
avoid error like:

`TypeError: __init__() missing 2 required positional arguments: 'nan'
and 'inf'`

## Changes

- Add default values for nan/inf fields in ColumnCountsMetric
- Add test to cover instantiating the ColumnCountsMetric with and
without nan/inf fields.

- [x] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md)
and the [Code of Conduct](CODE_OF_CONDUCT.md).